server:
  port: 8081
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        new_generator_mappings: true
        format_sql: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      globally_quoted_identifiers: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 050331shirley
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0



spring.mvc.pathmatch.matching-strategy: ant_path_matcher


swagger:
  enabled: true


